[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockTensorKit = "5f87ffc2-9cf1-4a46-8172-465d160bd8cd"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
MPSKitModels = "ca635005-6f8c-4cd1-b51d-8491250ef2ab"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
