[classic2d]
"1.hard-hexagon" = "b78b475bee20d0366789a01277b6242089c9a610290df012bd66ad880127553b"

[quantum1d]
"2.haldane" = "b81cbd6a4b9347be45acb779fa6e91b3c64c127d39e8a299aea64198ca24fba7"
"6.hubbard" = "f5710bddbb5bc7dc95b69978d45d70fe0a3d3d65dfbad66ad985d8977914c710"
"7.xy-finiteT" = "0f330a157bea739a43a82a937791c680b2fa6e5e479171ee5ef318d1fdae7bcf"
"8.bose-hubbard" = "a060ac3e29a9169e9420f7125cdb020c83b26a380508ac85f108bff1562bc70c"
"3.ising-dqpt" = "735882054a689df10ce0123c56fcc131d5d1156b8d12e9237d544e81b086250d"
"5.haldane-spt" = "9fce2c2d34c9e3a3b91dff3c3cba6404db6880fd92e66dcdfbbe7a6f3067495b"
"4.xxz-heisenberg" = "9033fb104c3f658ccb1b8e335b986b7abda59e0b5359be086d3b62e1cc32ebd6"
"1.ising-cft" = "ee6512b8e92aaaf42142b80024b905e9396aff75d4d60f77a29c18b234d1f65c"
