[classic2d]
"1.hard-hexagon" = "b380d99250b1908c03248a569ccb2729891f94ccad2a840dc9866af63ce98d2e"

[quantum1d]
"2.haldane" = "4f3e177a30df907cf7b9a47958ddf97741e4d0398ae1876e0f4977ccb93ae651"
"6.hubbard" = "a0f80e68edf8b12b90b1a7c8fe8e87d14be2f3dbea4fa0491ef53cf5eea0dbd7"
"7.xy-finiteT" = "0243b44634d38d04ddd96b180fd1fc24e20485e97135cb7c805c9d60baab9ccb"
"3.ising-dqpt" = "f437ac4560db51f67e3997867c02bb8844b1077731b1dd1a06c61ab7c4846e97"
"5.haldane-spt" = "6443696b20d416652951c646cf78b604a7fd0d79804995588491ea53ca210d57"
"1.ising-cft" = "f8e4987501c248a28dee6ada344e3638b515fdf28a451e6bb7ed22c0bec1fa8d"
"4.xxz-heisenberg" = "f8359ad29a028b01d41913014c0a442b99c3bd5cd403c23bd2a59f646a7c78cf"
