[classic2d]
"1.hard-hexagon" = "2c01966230ba56faa19a6751a734e53b8db744e7522b03b6a554662ccc76c550"

[quantum1d]
"2.haldane" = "804433b690faa1ce268a430edb4185af77a38de7a9f53e097795688a53c30c5e"
"6.hubbard" = "af14e1df11b2392a69260ce061a716370a2ce50b5c907f0a7d2548e796d543fe"
"7.xy-finiteT" = "7afb26fb9ff8ef84722fee3442eaed2ddffda4a5f70a7844b61ce5178093706c"
"8.bose-hubbard" = "665ee9e67ec428b771c0687ccebb232860f7373cfe1ac3081b35032e910dd9fc"
"3.ising-dqpt" = "2d314fd05a75c5c91ff81391c7bf166171b35a7b32933e9490756dc584fe8437"
"5.haldane-spt" = "3de1b3baa1e4c5dc2252bbe8688d0c6ac8e5d5265deeb6ab66818bbfb02dd4aa"
"4.xxz-heisenberg" = "1a2093a182f3ce070b53488484d1024e45496b291c1b74e3f370201d4c056be2"
"1.ising-cft" = "fc99e02aed275ca8f588a780a9de09ab09e16901681fcb72103e1e7dc4be157c"
