[deps]
BlockTensorKit = "5f87ffc2-9cf1-4a46-8172-465d160bd8cd"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
MPSKitModels = "ca635005-6f8c-4cd1-b51d-8491250ef2ab"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorKitTensors = "41b62e7d-e9d1-4e23-942c-79a97adf954b"

[sources]
MPSKit = {path = ".."}
