[[Trivial]]
mps_virtualspaces = ["ℂ^1", "ℂ^3", "ℂ^1"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^4", "ℂ^4", "ℂ^4"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^7", "ℂ^7", "ℂ^7"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^19", "ℂ^19", "ℂ^19"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^40", "ℂ^40", "ℂ^40"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^76", "ℂ^76", "ℂ^76"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^140", "ℂ^143", "ℂ^140"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^272", "ℂ^274", "ℂ^272"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^498 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]

[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 2, 1 => 1, -1 => 1)", "Rep[U₁](0 => 2, 1 => 1, -1 => 1)", "Rep[U₁](0 => 2, 1 => 1, -1 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 3, 1 => 2, -1 => 2)", "Rep[U₁](0 => 3, 1 => 2, -1 => 2)", "Rep[U₁](0 => 3, 1 => 2, -1 => 2)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 7, 1 => 5, -1 => 5, 2 => 1, -2 => 1)", "Rep[U₁](0 => 7, 1 => 5, -1 => 5, 2 => 1, -2 => 1)", "Rep[U₁](0 => 7, 1 => 5, -1 => 5, 2 => 1, -2 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 14, 1 => 10, -1 => 10, 2 => 3, -2 => 3)", "Rep[U₁](0 => 14, 1 => 10, -1 => 10, 2 => 3, -2 => 3)", "Rep[U₁](0 => 14, 1 => 10, -1 => 10, 2 => 3, -2 => 3)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 24, 1 => 18, -1 => 18, 2 => 7, -2 => 7, 3 => 1, -3 => 1)", "Rep[U₁](0 => 24, 1 => 18, -1 => 18, 2 => 7, -2 => 7, 3 => 1, -3 => 1)", "Rep[U₁](0 => 24, 1 => 18, -1 => 18, 2 => 7, -2 => 7, 3 => 1, -3 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 42, 1 => 32, -1 => 32, 2 => 14, -2 => 14, 3 => 3, -3 => 3)", "Rep[U₁](0 => 43, 1 => 33, -1 => 33, 2 => 14, -2 => 14, 3 => 3, -3 => 3)", "Rep[U₁](0 => 42, 1 => 32, -1 => 32, 2 => 14, -2 => 14, 3 => 3, -3 => 3)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 80, 1 => 62, -1 => 62, 2 => 28, -2 => 28, 3 => 6, -3 => 6)", "Rep[U₁](0 => 80, 1 => 63, -1 => 63, 2 => 28, -2 => 28, 3 => 6, -3 => 6)", "Rep[U₁](0 => 80, 1 => 62, -1 => 62, 2 => 28, -2 => 28, 3 => 6, -3 => 6)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>166, 1=>166, -1=>166) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]

[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 1)", "Rep[SU₂](1 => 1)", "Rep[SU₂](0 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 1, 1 => 1)", "Rep[SU₂](0 => 1, 1 => 1)", "Rep[SU₂](0 => 1, 1 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 1, 1 => 2)", "Rep[SU₂](0 => 1, 1 => 2)", "Rep[SU₂](0 => 1, 1 => 2)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 2, 1 => 4, 2 => 1)", "Rep[SU₂](0 => 2, 1 => 4, 2 => 1)", "Rep[SU₂](0 => 2, 1 => 4, 2 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 4, 1 => 7, 2 => 3)", "Rep[SU₂](0 => 4, 1 => 7, 2 => 3)", "Rep[SU₂](0 => 4, 1 => 7, 2 => 3)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 6, 1 => 11, 2 => 6, 3 => 1)", "Rep[SU₂](0 => 6, 1 => 11, 2 => 6, 3 => 1)", "Rep[SU₂](0 => 6, 1 => 11, 2 => 6, 3 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 10, 1 => 18, 2 => 11, 3 => 3)", "Rep[SU₂](0 => 10, 1 => 19, 2 => 11, 3 => 3)", "Rep[SU₂](0 => 10, 1 => 18, 2 => 11, 3 => 3)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 18, 1 => 34, 2 => 22, 3 => 6)", "Rep[SU₂](0 => 17, 1 => 35, 2 => 22, 3 => 6)", "Rep[SU₂](0 => 18, 1 => 34, 2 => 22, 3 => 6)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 28, 1 => 58, 2 => 43, 3 => 14, 4 => 1)", "Rep[SU₂](0 => 30, 1 => 59, 2 => 43, 3 => 13, 4 => 1)", "Rep[SU₂](0 => 28, 1 => 58, 2 => 43, 3 => 14, 4 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 41, 1 => 84, 2 => 64, 3 => 26, 4 => 11, 5 => 6, 6 => 3)", "Rep[SU₂](0 => 34, 1 => 71, 2 => 63, 3 => 30, 4 => 12, 5 => 6, 6 => 3, 7 => 1)", "Rep[SU₂](0 => 40, 1 => 83, 2 => 62, 3 => 29, 4 => 12, 5 => 7, 6 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]], [[1, 1], [3, 3], [2, 2], [2, 3], [1, 2], [1, 3]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>166) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
