[[Trivial]]
mps_virtualspaces = ["ℂ^3", "ℂ^1", "ℂ^3"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^7", "ℂ^7", "ℂ^7"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^16", "ℂ^16", "ℂ^16"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^44", "ℂ^44", "ℂ^44"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^108", "ℂ^108", "ℂ^108"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^271", "ℂ^271", "ℂ^271"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]
[[Trivial]]
mps_virtualspaces = ["ℂ^661", "ℂ^667", "ℂ^669"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)", "(ℂ^1 ⊞ ℂ^3 ⊞ ℂ^1)"]
physicalspaces = ["ℂ^3", "ℂ^3"]

[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 3, 1 => 2, -1 => 2)", "Rep[U₁](0 => 3, 1 => 2, -1 => 2)", "Rep[U₁](0 => 3, 1 => 2, -1 => 2)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 6, 1 => 4, -1 => 4, 2 => 1, -2 => 1)", "Rep[U₁](0 => 6, 1 => 4, -1 => 4, 2 => 1, -2 => 1)", "Rep[U₁](0 => 6, 1 => 4, -1 => 4, 2 => 1, -2 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 12, 1 => 10, -1 => 10, 2 => 5, -2 => 5, 3 => 1, -3 => 1)", "Rep[U₁](0 => 12, 1 => 10, -1 => 10, 2 => 5, -2 => 5, 3 => 1, -3 => 1)", "Rep[U₁](0 => 12, 1 => 10, -1 => 10, 2 => 5, -2 => 5, 3 => 1, -3 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 32, 1 => 25, -1 => 25, 2 => 11, -2 => 11, 3 => 2, -3 => 2)", "Rep[U₁](0 => 32, 1 => 25, -1 => 25, 2 => 11, -2 => 11, 3 => 2, -3 => 2)", "Rep[U₁](0 => 32, 1 => 25, -1 => 25, 2 => 11, -2 => 11, 3 => 2, -3 => 2)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 71, 1 => 58, -1 => 58, 2 => 31, -2 => 31, 3 => 10, -3 => 10, 4 => 1, -4 => 1)", "Rep[U₁](0 => 71, 1 => 58, -1 => 58, 2 => 31, -2 => 31, 3 => 10, -3 => 10, 4 => 1, -4 => 1)", "Rep[U₁](0 => 71, 1 => 58, -1 => 58, 2 => 31, -2 => 31, 3 => 10, -3 => 10, 4 => 1, -4 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 153, 1 => 130, -1 => 130, 2 => 79, -2 => 79, 3 => 33, -3 => 33, 4 => 10, -4 => 10, 5 => 2, -5 => 2)", "Rep[U₁](0 => 157, 1 => 133, -1 => 133, 2 => 80, -2 => 80, 3 => 33, -3 => 33, 4 => 8, -4 => 8, 5 => 1, -5 => 1)", "Rep[U₁](0 => 159, 1 => 134, -1 => 134, 2 => 80, -2 => 80, 3 => 32, -3 => 32, 4 => 8, -4 => 8, 5 => 1, -5 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 307, 1 => 273, -1 => 273, 2 => 194, -2 => 194, 3 => 114, -3 => 114, 4 => 58, -4 => 58, 5 => 24, -5 => 24, 6 => 6, -6 => 6, 7 => 1, -7 => 1)", "Rep[U₁](0 => 317, 1 => 280, -1 => 280, 2 => 194, -2 => 194, 3 => 110, -3 => 110, 4 => 53, -4 => 53, 5 => 20, -5 => 20, 6 => 5, -6 => 5, 7 => 1, -7 => 1)", "Rep[U₁](0 => 313, 1 => 278, -1 => 278, 2 => 196, -2 => 196, 3 => 114, -3 => 114, 4 => 56, -4 => 56, 5 => 20, -5 => 20, 6 => 4, -6 => 4)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]
[["Irrep[U₁]"]]
mps_virtualspaces = ["Rep[U₁](0 => 987, 1 => 830, -1 => 830, 2 => 432, -2 => 432, 3 => 161, -3 => 161, 4 => 77, -4 => 77, 5 => 28, -5 => 28, 6 => 7, -6 => 7, 7 => 1, -7 => 1)", "Rep[U₁](0 => 701, 1 => 635, -1 => 635, 2 => 478, -2 => 478, 3 => 303, -3 => 303, 4 => 162, -4 => 162, 5 => 70, -5 => 70, 6 => 22, -6 => 22, 7 => 4, -7 => 4)", "Rep[U₁](0 => 987, 1 => 830, -1 => 830, 2 => 431, -2 => 431, 3 => 161, -3 => 161, 4 => 77, -4 => 77, 5 => 28, -5 => 28, 6 => 7, -6 => 7, 7 => 1, -7 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))", "(Rep[U₁](0=>1) ⊞ Rep[U₁](0=>1, 1=>1, -1=>1) ⊞ Rep[U₁](0=>1))"]
physicalspaces = ["Rep[U₁](0 => 1, 1 => 1, -1 => 1)", "Rep[U₁](0 => 1, 1 => 1, -1 => 1)"]

[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](0 => 1)", "Rep[SU₂](1 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 1, 1 => 2)", "Rep[SU₂](0 => 1, 1 => 2)", "Rep[SU₂](0 => 1, 1 => 2)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 2, 1 => 3, 2 => 1)", "Rep[SU₂](0 => 2, 1 => 3, 2 => 1)", "Rep[SU₂](0 => 2, 1 => 3, 2 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 2, 1 => 5, 2 => 4, 3 => 1)", "Rep[SU₂](0 => 2, 1 => 5, 2 => 4, 3 => 1)", "Rep[SU₂](0 => 2, 1 => 5, 2 => 4, 3 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 7, 1 => 14, 2 => 9, 3 => 2)", "Rep[SU₂](0 => 7, 1 => 14, 2 => 9, 3 => 2)", "Rep[SU₂](0 => 7, 1 => 14, 2 => 9, 3 => 2)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 13, 1 => 27, 2 => 21, 3 => 9, 4 => 1)", "Rep[SU₂](0 => 13, 1 => 27, 2 => 21, 3 => 9, 4 => 1)", "Rep[SU₂](0 => 13, 1 => 27, 2 => 21, 3 => 9, 4 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 23, 1 => 51, 2 => 46, 3 => 23, 4 => 8, 5 => 2)", "Rep[SU₂](0 => 24, 1 => 53, 2 => 47, 3 => 25, 4 => 7, 5 => 1)", "Rep[SU₂](0 => 25, 1 => 54, 2 => 48, 3 => 24, 4 => 7, 5 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 34, 1 => 79, 2 => 80, 3 => 56, 4 => 34, 5 => 18, 6 => 5, 7 => 1)", "Rep[SU₂](0 => 37, 1 => 86, 2 => 84, 3 => 57, 4 => 33, 5 => 15, 6 => 4, 7 => 1)", "Rep[SU₂](0 => 35, 1 => 82, 2 => 82, 3 => 58, 4 => 36, 5 => 16, 6 => 4)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 157, 1 => 398, 2 => 271, 3 => 84, 4 => 49, 5 => 21, 6 => 6, 7 => 1)", "Rep[SU₂](0 => 66, 1 => 157, 2 => 175, 3 => 141, 4 => 92, 5 => 48, 6 => 18, 7 => 4)", "Rep[SU₂](0 => 157, 1 => 399, 2 => 270, 3 => 84, 4 => 49, 5 => 21, 6 => 6, 7 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
[["Irrep[SU₂]"]]
mps_virtualspaces = ["Rep[SU₂](0 => 1196, 1 => 1678, 2 => 483, 3 => 84, 4 => 49, 5 => 21, 6 => 6, 7 => 1)", "Rep[SU₂](0 => 603, 1 => 1213, 2 => 280, 3 => 237, 4 => 153, 5 => 76, 6 => 28, 7 => 7, 8 => 1)", "Rep[SU₂](0 => 1198, 1 => 1646, 2 => 502, 3 => 84, 4 => 49, 5 => 21, 6 => 6, 7 => 1)"]
nonzero_keys = [[[1, 1], [3, 3], [2, 3], [1, 2]], [[1, 1], [3, 3], [2, 3], [1, 2]]]
mpo_virtualspaces = ["(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))", "(Rep[SU₂](0=>1) ⊞ Rep[SU₂](1=>1) ⊞ Rep[SU₂](0=>1))"]
physicalspaces = ["Rep[SU₂](1 => 1)", "Rep[SU₂](1 => 1)"]
