name: Tests
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'release-'
    tags: '*'
    paths-ignore:
      - 'docs/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel intermediate builds: only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  tests-draft:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft }}
    name: "Tests - draft mode"
    strategy:
      fail-fast: false
      matrix:
        group:
          - states
          - operators
          - algorithms
          - multifusion
          - misc
    uses: "QuantumKitHub/QuantumKitHubActions/.github/workflows/Tests.yml@main"
    with:
      group: "${{ matrix.group }}"
      nthreads: 4
      # julia-version: "${{ matrix.version }}"
      # os: "${{ matrix.os }}"
      timeout-minutes: 120
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  tests:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts' # minimal supported version
          - '1' # latest released Julia version
        group:
          - states
          - operators
          - algorithms
          - multifusion
          - misc
        os:
          - macOS-latest
          - windows-latest
          - ubuntu-latest
    uses: "QuantumKitHub/QuantumKitHubActions/.github/workflows/Tests.yml@main"
    with:
      group: "${{ matrix.group }}"
      nthreads: 4
      julia-version: "${{ matrix.version }}"
      os: "${{ matrix.os }}"
      timeout-minutes: 120
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
