name: Tests
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'release-'
    tags: '*'
    paths-ignore:
      - 'docs/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel intermediate builds: only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  tests-draft:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft }}
    name: "Draft"
    strategy:
      fail-fast: false
      matrix:
        group:
          - states
          - operators
          - algorithms
          - multifusion
          - misc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: 1
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          test_args: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: 'src,ext'
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: "${{ secrets.CODECOV_TOKEN }}"
          fail_ci_if_error: true

  tests:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        version: ['lts', '1']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        group:
          - states
          - operators
          - algorithms
          - multifusion
          - misc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          test_args: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: 'src,ext'
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: "${{ secrets.CODECOV_TOKEN }}"
          fail_ci_if_error: true
